---
- name: Get serial number of Cisco switches
  hosts: switch
  gather_facts: no
  connection: paramiko   # Use Paramiko for the connection
  tasks:
    - name: Gather facts from Cisco switches
      ios_facts:
        gather_subset: hardware

    - name: Display serial number
      debug:
        var: ansible_net_serialnum
